package org.nixdork.klog.common

// Crypto
const val CRYPTO_HASH_ALGORITHM = "SHA3-256"
const val CRYPTO_HASH_ALGORITHM2 = "PBKDF2WithHmacSHA512"
const val CRYPTO_HASH_ITERATIONS = 120_000
const val CRYPTO_HASH_KEY_LENGTH = 256
const val CRYPTO_HASH_SECRET = "SomeRandomSecret"
const val CRYPTO_SALT_ALGORITHM = "NativePRNGNonBlocking"
const val CRYPTO_BYTES_TO_GENERATE = 16

// DataSource
const val DATASOURCE_CONNECTION_TIMEOUT = 30L
const val DATASOURCE_KEEP_ALIVE_TIME = 0L
const val DATASOURCE_MAX_LIFETIME = 30L
const val DATASOURCE_MAX_POOL_SIZE = 10
const val DATASOURCE_LEAK_DETECTION_THRESHOLD = 10L
const val DATASOURCE_VALIDATION_TIMEOUT = 5L
