package org.nixdork.klog.common

// Crypto
const val CRYPTO_HASH_RANDOM_ALGORITHM = "SHA3-256"
const val CRYPTO_SALT_RANDOM_ALGORITHM = "NativePRNGNonBlocking"
const val CRYPTO_BYTES_TO_GENERATE = 16

// DataSource
const val DATASOURCE_CONNECTION_TIMEOUT = 30L
const val DATASOURCE_KEEP_ALIVE_TIME = 0L
const val DATASOURCE_MAX_LIFETIME = 30L
const val DATASOURCE_MAX_POOL_SIZE = 10
const val DATASOURCE_LEAK_DETECTION_THRESHOLD = 10L
const val DATASOURCE_VALIDATION_TIMEOUT = 5L
